In [2]:
import pandas as pd
import numpy as np

products = pd.read_csv("D:/Dare X AI/Data/products.csv")
outfits = pd.read_csv("D:/Dare X AI/Data/outfits.csv")

In [3]:
user_profile = {
    "gender":"women",
    "occasion":"party",
    "wear_type":"western"
}

In [4]:
def calculate_score(
    outfit,
    user_profile
):

    score = 0

    # Gender Match
    if outfit["gender"].lower() == user_profile["gender"].lower():
        score += 40

    # Occasion Match
    if outfit["occasion"].lower() == user_profile["occasion"].lower():
        score += 40

    # Wear Type Match
    if outfit["wear_type"].lower() == user_profile["wear_type"].lower():
        score += 20

    return score

In [5]:
calculate_score(
    outfits.iloc[0],
    user_profile
)

100

In [6]:
scores = []

for _, outfit in outfits.iterrows():

    score = calculate_score(
        outfit,
        user_profile
    )

    scores.append(score)

outfits["score"] = scores

In [7]:
outfits[
[
    "theme",
    "occasion",
    "wear_type",
    "score"
]
].head()

                     theme occasion wear_type  score
0           Black cocktail    party   western    100
1     Wine bodycon evening    party   western    100
2  Magenta slip, night out    party   western    100
3      Dusty-blue Anarkali  festive    ethnic     40
4       Red Banarasi saree  wedding    ethnic     40

In [8]:
ranked_outfits = outfits.sort_values(
    by="score",
    ascending=False
)

ranked_outfits.head(10)

,outfit_id,gender,wear_type,occasion,theme,hero,hero_id,second,second_id,layer,...,accessory_1,accessory_1_id,accessory_2,accessory_2_id,palette,items_count,total_price_inr,image_files,stylist_rationale,score
0,outfit W1,women,western,party,Black cocktail,Women Bodycon Midi Length Dress (Fyre Rose),ajio_703182002,NaN,NaN,NaN,...,Sparkle Framed Clutch (Lavie),myntra_15660676,NaN,NaN,black / red,3,2313,images/ajio/703182002.jpg;images/myntra/425402...,Black midi with a gold chain waist detail; gol...,100
1,outfit W2,women,western,party,Wine bodycon evening,Bodycon Midi Dress (MULVARI),myntra_41733768,NaN,NaN,NaN,...,Women Embellished Clutch with Lock (Rubans),ajio_701677398,NaN,NaN,maroon / red / white,3,1977,images/myntra/41733768.jpg;images/myntra/31751...,Sleek wine square-neck bodycon; nude-tan kitte...,100
2,outfit W3,women,western,party,"Magenta slip, night out",Ruched Asymmetrical Midi Dress (MANGO),myntra_34682942,NaN,NaN,NaN,...,Sling Bag with Quilted (Exotic),myntra_24130018,NaN,NaN,red / white / black,3,3870,images/myntra/34682942.jpg;images/myntra/32069...,Magenta ruched slip dress with white pointed a...,100
13,outfit W14,women,western,party,Blush statement maxi,Marquee White Sequin Printed Dress (VERO MODA),nykaa_20942213,NaN,NaN,NaN,...,Sparkle Framed Clutch (Lavie),myntra_15660676,NaN,NaN,white / red,3,6023,images/nykaa/20942213.jpg;images/myntra/317511...,Blush printed slip maxi; nude-tan kitten heels...,100
9,outfit W10,women,western,party,Mocha satin co-ord,Women 2-Piece Co-Ord Set (Lulu & Sky),ajio_703543037,NaN,NaN,NaN,...,Sling Bag with Quilted (Exotic),myntra_24130018,NaN,NaN,brown / black,3,4491,images/ajio/703543037.jpg;images/ajio/70239024...,A matching mocha satin cami + wrap skirt does ...,100
8,outfit W9,women,western,vacation,Navy-floral maxi,Women Floral Print Maxi Fit & Flare Dress (LEIA),ajio_701467182,NaN,NaN,NaN,...,Shopper Shoulder Bag (MANGO),myntra_36090580,Brown UV Protection Oval Full Rim Casual Women...,nykaa_22909654,navy / brown / olive,4,3607,images/ajio/701467182.jpg;images/ajio/70239024...,Flowy navy maxi printed with cream lilies; fla...,60
11,outfit W12,women,western,winter,Grey-coat layers,Open Knit Pullover Sweater (Roadster),myntra_11990814,Women Straight Fit High-Rise Jeans (U.S. Polo ...,myntra_41163758,Button Closure Long Coat (Cantabil),...,NaN,NaN,NaN,NaN,red / blue / grey / black,4,8032,images/myntra/11990814.jpg;images/myntra/41163...,Rust waffle-knit sweater and light jeans under...,60
7,outfit W8,women,western,casual,Light-denim day,Floral Print Peplum Top (Anouk Mirage),myntra_39522716,Women Straight Fit High-Rise Jeans (U.S. Polo ...,myntra_41163758,NaN,...,Sling Bag with Quilted (Exotic),myntra_24130018,Brown UV Protection Oval Full Rim Casual Women...,nykaa_22909654,white / blue / cream / black / brown,5,4825,images/myntra/39522716.jpg;images/myntra/41163...,Cream floral peplum top with light wide-leg je...,60
6,outfit W7,women,western,office,Navy-floral workwear,Women Navy Blue Print Long Sleeves Formal Shir...,nykaa_21896203,Women Olive Green High Rise Formal Trousers (P...,nykaa_19331662,Single-Breasted Formal Blazers (Van Heusen Woman),...,Shopper Shoulder Bag (MANGO),myntra_36090580,NaN,NaN,navy / green / white / olive,5,8358,images/nykaa/21896203.jpg;images/nykaa/1933166...,Navy floral satin shirt with olive wide-leg tr...,60
12,outfit W13,women,western,casual,Maroon shirt + denim skirt,Formal Shirt (Chemistry),myntra_30308778,Women Solid Bright Blue Bonnet Midi Skirt (KOTTY),nykaa_21742536,NaN,...,Sling Bag with Quilted (Exotic),myntra_24130018,NaN,NaN,maroon / blue / cream / black,4,3401,images/myntra/30308778.jpg;images/nykaa/217425...,Maroon utility shirt with a light-denim midi s...,60

In [ ]:
def recommend_top_k(
    user_profile,
    k=5
):

    scores = []

    for _, outfit in outfits.iterrows():

        score = calculate_score(
            outfit,
            user_profile
        )

        scores.append(score)

    temp = outfits.copy()

    temp["score"] = scores

    temp = temp.sort_values(
        by="score",
        ascending=False
    )

    return temp.head(k)

In [10]:
recommend_top_k(
    {
        "gender":"women",
        "occasion":"party",
        "wear_type":"western"
    }
)

,outfit_id,gender,wear_type,occasion,theme,hero,hero_id,second,second_id,layer,...,accessory_1,accessory_1_id,accessory_2,accessory_2_id,palette,items_count,total_price_inr,image_files,stylist_rationale,score
0,outfit W1,women,western,party,Black cocktail,Women Bodycon Midi Length Dress (Fyre Rose),ajio_703182002,NaN,NaN,NaN,...,Sparkle Framed Clutch (Lavie),myntra_15660676,NaN,NaN,black / red,3,2313,images/ajio/703182002.jpg;images/myntra/425402...,Black midi with a gold chain waist detail; gol...,100
1,outfit W2,women,western,party,Wine bodycon evening,Bodycon Midi Dress (MULVARI),myntra_41733768,NaN,NaN,NaN,...,Women Embellished Clutch with Lock (Rubans),ajio_701677398,NaN,NaN,maroon / red / white,3,1977,images/myntra/41733768.jpg;images/myntra/31751...,Sleek wine square-neck bodycon; nude-tan kitte...,100
2,outfit W3,women,western,party,"Magenta slip, night out",Ruched Asymmetrical Midi Dress (MANGO),myntra_34682942,NaN,NaN,NaN,...,Sling Bag with Quilted (Exotic),myntra_24130018,NaN,NaN,red / white / black,3,3870,images/myntra/34682942.jpg;images/myntra/32069...,Magenta ruched slip dress with white pointed a...,100
13,outfit W14,women,western,party,Blush statement maxi,Marquee White Sequin Printed Dress (VERO MODA),nykaa_20942213,NaN,NaN,NaN,...,Sparkle Framed Clutch (Lavie),myntra_15660676,NaN,NaN,white / red,3,6023,images/nykaa/20942213.jpg;images/myntra/317511...,Blush printed slip maxi; nude-tan kitten heels...,100
9,outfit W10,women,western,party,Mocha satin co-ord,Women 2-Piece Co-Ord Set (Lulu & Sky),ajio_703543037,NaN,NaN,NaN,...,Sling Bag with Quilted (Exotic),myntra_24130018,NaN,NaN,brown / black,3,4491,images/ajio/703543037.jpg;images/ajio/70239024...,A matching mocha satin cami + wrap skirt does ...,100

In [11]:
top5 = recommend_top_k(
    {
        "gender":"women",
        "occasion":"party",
        "wear_type":"western"
    }
)

top5[
[
    "theme",
    "hero",
    "footwear",
    "score"
]
]

,theme,hero,footwear,score
0,Black cocktail,Women Bodycon Midi Length Dress (Fyre Rose),Classic Women's Heels (Lavie),100
1,Wine bodycon evening,Bodycon Midi Dress (MULVARI),Open Toe Kitten Heel Sandals (Mochi),100
2,"Magenta slip, night out",Ruched Asymmetrical Midi Dress (MANGO),Women Stiletto Pumps (Shoetopia),100
13,Blush statement maxi,Marquee White Sequin Printed Dress (VERO MODA),Open Toe Kitten Heel Sandals (Mochi),100
9,Mocha satin co-ord,Women 2-Piece Co-Ord Set (Lulu & Sky),Women Slip-On Flat Sandals (JM LOOKS),100